### ISSUE TITLE
Metadata error when trying to run setup

### ISSUE THREAD

**Issue by 3urobeat** [vladmandic/piproxy#2]
Hey!
I wanted to try out this project but ran into this error multiple times when trying to run setup.js

Log:
```
PS Path\piproxy-1.0.0> node setup.js
Starting Setup
piproxy server v0.0.5
Platform=win32 Arch=x64 Node=v14.15.0
Project dependencies
 production: 10
 development: 10
 optional: 0
NPM install production modules completed in 9.463ms
NPM install development modules completed in 36.161ms
NPM install optional modules completed in 4.773ms
NCU force upgrade modules
NPM update modules completed in 21.876ms
NPM deduplicate modules completed in 3.575ms
NPM prune unused modules completed in 4.419ms
NPM audit modules completed in 2.104ms
Deleting module samples completed in 11ms
NPM outdated check completed in 6.031ms
NPM indirect outdated modules: 81
NPM list full completed in 2.460ms
Path\piproxy-1.0.0\node_modules\npm-check-updates\lib\npm-check-updates.js:353
  throw err
  ^

TypeError: Cannot read property 'metadata' of undefined
    at main (Path\piproxy-1.0.0\setup.js:104:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

...which will the result in an error when trying to start with `npm start`: `Error: Cannot find module '../cert/secrets.json'`

OS: Win10 2004 (haven't tried on my Linux machine yet)

**Comment by vladmandic** [comment]
this shows you're using `piproxy` version 0.0.5? if so, that is a very old version and this issue has been fixed.  
latest version is 1.1.4.  

```log
$ node setup.js
Starting Setup
@vladmandic/piproxy server v1.1.4
Platform=linux Arch=x64 Node=v15.0.1
Project dependencies
 production: 9
 development: 8
 optional: 0
NPM install production modules completed in 4,783ms
NPM install development modules completed in 4,982ms
NPM install optional modules completed in 4,544ms
Skipping NCU force upgrade modules
NPM update modules completed in 11,898ms
NPM deduplicate modules completed in 3,194ms
NPM prune unused modules completed in 3,846ms
NPM audit modules completed in 4,113ms
Deleting module samples completed in 42ms
NPM outdated check completed in 4,690ms
NPM indirect outdated modules: 40
NPM list full completed in 2,346ms
Total dependencies: production=84 development=443 optional=2
Results written to setup.json
```

**Comment by 3urobeat** [comment]
Hm well seems that that is the case.
I downloaded it by clicking on "or download and unpack from https://github.com/vladmandic/piproxy/releases/" in the README so I didn't realise it might be an old version.
But I see you published a new release just now and the setup seems to be working fine now.

**Comment by vladmandic** [comment]
i saw that when you reported the issue - i rarely update releases for my projects as majority of usage comes from git itself (git clone or git fork).

closing as resolved.
